import {
  Users,
  CheckCircle,
  AlertTriangle,
  MessageSquare,
  Heart,
  FileText,
  ShieldAlert,
  Clock,
  Activity,
} from "lucide-react";
import { ICONS } from "./icons";
import { images } from "./images";

export const INITIAL_STATS: StatsData = {
  totalUsers: 1250,
  verifiedUsers: 890,
  pendingVerifications: 45,
  newComplaints: 12,
  activeChats: 234,
  marriageRequests: 67,
  reportedChats: 8,
  bannedUsers: 23,
};

export const RECENT_ACTIVITIES = [
  {
    id: 1,
    user: "Ahmed Mohamed",
    action: "New registration",
    time: "5 minutes ago",
    type: "user" as const,
    urgent: false,
    avatar: images.avatar,
  },
  {
    id: 2,
    user: "Fatima Ali",
    action: "Uploaded verification documents",
    time: "15 minutes ago",
    type: "verification" as const,
    urgent: true,
    avatar: images.avatar,
  },
  {
    id: 3,
    user: "Mohammed Khaled",
    action: "New complaint",
    time: "30 minutes ago",
    type: "complaint" as const,
    urgent: true,
    avatar: images.avatar,
  },
  {
    id: 4,
    user: "Sara Abdullah",
    action: "Marriage request",
    time: "45 minutes ago",
    type: "marriage" as const,
    urgent: false,
    avatar: images.avatar,
  },
];

export const QUICK_ACTIONS = (stats: StatsData): QuickAction[] => [
  {
    icon: ICONS.users,
    label: "Manage Users",
    href: "/admin/users",
    count: stats.totalUsers,
    color: "text-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
  },
  {
    icon: ICONS.verifications,
    label: "Review Verification",
    href: "/admin/verification",
    count: stats.pendingVerifications,
    color: "text-amber-600",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
  },
  {
    icon: ICONS.complain,
    label: "Handle Complaints",
    href: "/admin/complaints",
    count: stats.newComplaints,
    color: "text-red-600",
    bgColor: "bg-red-50 dark:bg-red-950/20",
  },
  {
    icon: ICONS.marriageRequests,
    label: "Marriage Requests",
    href: "/admin/marriage-requests",
    count: stats.marriageRequests,
    color: "text-pink-600",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
  },
  {
    icon: ICONS.chats,
    label: "Active Chats",
    href: "/admin/chats",
    count: stats.activeChats,
    color: "text-green-600",
    bgColor: "bg-green-50 dark:bg-green-950/20",
  },
  {
    icon: ICONS.analytics,
    label: "Analytics",
    href: "/admin/analytics",
    color: "text-purple-600",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
  },
];

export const sampleUsers = [
  {
    id: 1,
    name: "Ahmed Mohamed",
    email: "ahmed@example.com",
    phone: "+966501234567",
    status: "active",
    verification: "verified",
    registrationDate: "2024-01-15",
    lastLogin: "2024-03-20",
    reportsCount: 0,
    marriageRequests: 3,
    activeChats: 5,
  },
  {
    id: 2,
    name: "Fatima Ali",
    email: "fatima@example.com",
    phone: "+966502345678",
    status: "pending",
    verification: "pending",
    registrationDate: "2024-02-20",
    lastLogin: "2024-03-19",
    reportsCount: 0,
    marriageRequests: 1,
    activeChats: 2,
  },
  {
    id: 3,
    name: "Mohammed Khaled",
    email: "mohammed@example.com",
    phone: "+966503456789",
    status: "banned",
    verification: "verified",
    registrationDate: "2024-01-10",
    lastLogin: "2024-03-18",
    reportsCount: 3,
    marriageRequests: 0,
    activeChats: 0,
  },
  {
    id: 4,
    name: "Sara Abdullah",
    email: "sara@example.com",
    phone: "+966504567890",
    status: "active",
    verification: "verified",
    registrationDate: "2024-02-05",
    lastLogin: "2024-03-20",
    reportsCount: 1,
    marriageRequests: 2,
    activeChats: 3,
  },
  {
    id: 5,
    name: "Khaled Saeed",
    email: "khaled@example.com",
    phone: "+966505678901",
    status: "inactive",
    verification: "unverified",
    registrationDate: "2024-03-01",
    lastLogin: "2024-03-10",
    reportsCount: 0,
    marriageRequests: 0,
    activeChats: 1,
  },
  {
    id: 1,
    name: "Ahmed Mohamed",
    email: "ahmed@example.com",
    phone: "+966501234567",
    status: "active",
    verification: "verified",
    registrationDate: "2024-01-15",
    lastLogin: "2024-03-20",
    reportsCount: 0,
    marriageRequests: 3,
    activeChats: 5,
  },
  {
    id: 2,
    name: "Fatima Ali",
    email: "fatima@example.com",
    phone: "+966502345678",
    status: "pending",
    verification: "pending",
    registrationDate: "2024-02-20",
    lastLogin: "2024-03-19",
    reportsCount: 0,
    marriageRequests: 1,
    activeChats: 2,
  },
  {
    id: 3,
    name: "Mohammed Khaled",
    email: "mohammed@example.com",
    phone: "+966503456789",
    status: "banned",
    verification: "verified",
    registrationDate: "2024-01-10",
    lastLogin: "2024-03-18",
    reportsCount: 3,
    marriageRequests: 0,
    activeChats: 0,
  },
  {
    id: 4,
    name: "Sara Abdullah",
    email: "sara@example.com",
    phone: "+966504567890",
    status: "active",
    verification: "verified",
    registrationDate: "2024-02-05",
    lastLogin: "2024-03-20",
    reportsCount: 1,
    marriageRequests: 2,
    activeChats: 3,
  },
  {
    id: 5,
    name: "Khaled Saeed",
    email: "khaled@example.com",
    phone: "+966505678901",
    status: "inactive",
    verification: "unverified",
    registrationDate: "2024-03-01",
    lastLogin: "2024-03-10",
    reportsCount: 0,
    marriageRequests: 0,
    activeChats: 1,
  },
  {
    id: 1,
    name: "Ahmed Mohamed",
    email: "ahmed@example.com",
    phone: "+966501234567",
    status: "active",
    verification: "verified",
    registrationDate: "2024-01-15",
    lastLogin: "2024-03-20",
    reportsCount: 0,
    marriageRequests: 3,
    activeChats: 5,
  },
  {
    id: 2,
    name: "Fatima Ali",
    email: "fatima@example.com",
    phone: "+966502345678",
    status: "pending",
    verification: "pending",
    registrationDate: "2024-02-20",
    lastLogin: "2024-03-19",
    reportsCount: 0,
    marriageRequests: 1,
    activeChats: 2,
  },
  {
    id: 3,
    name: "Mohammed Khaled",
    email: "mohammed@example.com",
    phone: "+966503456789",
    status: "banned",
    verification: "verified",
    registrationDate: "2024-01-10",
    lastLogin: "2024-03-18",
    reportsCount: 3,
    marriageRequests: 0,
    activeChats: 0,
  },
  {
    id: 4,
    name: "Sara Abdullah",
    email: "sara@example.com",
    phone: "+966504567890",
    status: "active",
    verification: "verified",
    registrationDate: "2024-02-05",
    lastLogin: "2024-03-20",
    reportsCount: 1,
    marriageRequests: 2,
    activeChats: 3,
  },
  {
    id: 5,
    name: "Khaled Saeed",
    email: "khaled@example.com",
    phone: "+966505678901",
    status: "inactive",
    verification: "unverified",
    registrationDate: "2024-03-01",
    lastLogin: "2024-03-10",
    reportsCount: 0,
    marriageRequests: 0,
    activeChats: 1,
  },
  {
    id: 1,
    name: "Ahmed Mohamed",
    email: "ahmed@example.com",
    phone: "+966501234567",
    status: "active",
    verification: "verified",
    registrationDate: "2024-01-15",
    lastLogin: "2024-03-20",
    reportsCount: 0,
    marriageRequests: 3,
    activeChats: 5,
  },
  {
    id: 2,
    name: "Fatima Ali",
    email: "fatima@example.com",
    phone: "+966502345678",
    status: "pending",
    verification: "pending",
    registrationDate: "2024-02-20",
    lastLogin: "2024-03-19",
    reportsCount: 0,
    marriageRequests: 1,
    activeChats: 2,
  },
  {
    id: 3,
    name: "Mohammed Khaled",
    email: "mohammed@example.com",
    phone: "+966503456789",
    status: "banned",
    verification: "verified",
    registrationDate: "2024-01-10",
    lastLogin: "2024-03-18",
    reportsCount: 3,
    marriageRequests: 0,
    activeChats: 0,
  },
  {
    id: 4,
    name: "Sara Abdullah",
    email: "sara@example.com",
    phone: "+966504567890",
    status: "active",
    verification: "verified",
    registrationDate: "2024-02-05",
    lastLogin: "2024-03-20",
    reportsCount: 1,
    marriageRequests: 2,
    activeChats: 3,
  },
  {
    id: 5,
    name: "Khaled Saeed",
    email: "khaled@example.com",
    phone: "+966505678901",
    status: "inactive",
    verification: "unverified",
    registrationDate: "2024-03-01",
    lastLogin: "2024-03-10",
    reportsCount: 0,
    marriageRequests: 0,
    activeChats: 1,
  },
];

export const NOTIFICATION_TYPES = {
  success: {
    label: "Success",
    color: "text-green-600",
    bgColor: "bg-green-500",
  },
  error: {
    label: "Error",
    color: "text-red-600",
    bgColor: "bg-red-500",
  },
  warning: {
    label: "Warning",
    color: "text-amber-600",
    bgColor: "bg-amber-500",
  },
  info: {
    label: "Info",
    color: "text-blue-600",
    bgColor: "bg-blue-500",
  },
  user: {
    label: "User Activity",
    color: "text-purple-600",
    bgColor: "bg-primary-color1",
  },
  system: {
    label: "System",
    color: "text-gray-600",
    bgColor: "bg-blue-500",
  },
};

export const SAMPLE_NOTIFICATIONS = [
  {
    id: "1",
    type: "user",
    title: "New User Registration",
    message: "Ahmed Mohamed has registered on the platform",
    timestamp: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
    read: false,
    priority: "medium",
    actionUrl: "/admin/users/123",
    userId: "123",
    userName: "Ahmed Mohamed",
  },
  {
    id: "2",
    type: "success",
    title: "Verification Approved",
    message: "User verification for Fatima Ali has been approved",
    timestamp: new Date(Date.now() - 15 * 60 * 1000), // 15 minutes ago
    read: true,
    priority: "low",
    actionUrl: "/admin/verification",
  },
  {
    id: "3",
    type: "error",
    title: "System Error",
    message: "Payment processing service encountered an error",
    timestamp: new Date(Date.now() - 30 * 60 * 1000), // 30 minutes ago
    read: false,
    priority: "high",
  },
  {
    id: "4",
    type: "warning",
    title: "Suspicious Activity",
    message: "Multiple login attempts detected for user account",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    read: true,
    priority: "high",
    actionUrl: "/admin/security",
  },
  {
    id: "5",
    type: "info",
    title: "System Maintenance",
    message: "Scheduled maintenance will occur tonight at 2:00 AM",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    read: true,
    priority: "medium",
  },
  {
    id: "6",
    type: "user",
    title: "Profile Update",
    message: "Mohammed Khaled has updated their profile information",
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    read: false,
    priority: "low",
    userId: "456",
    userName: "Mohammed Khaled",
  },
];
