import { User, Eye, Coffee, BookOpen, GraduationCap } from "lucide-react";

const FIELD_OPTIONS = {
  gender: ["Male", "Female"],
  bodyStyle: ["Slim", "Athletic", "Average", "Muscular", "Curvy", "Plus Size"],
  ethnicity: [
    "Middle Eastern",
    "Asian",
    "African",
    "European",
    "Hispanic/Latino",
    "Mixed",
    "Other",
  ],
  hairColor: [
    "Black",
    "Brown",
    "Blonde",
    "Red",
    "Auburn",
    "Grey",
    "White",
    "Other",
  ],
  eyeColor: ["Brown", "Hazel", "Blue", "Green", "Grey", "Black", "Other"],
  smoke: ["Non-smoker", "Smoker", "Occasionally"],
  maritalStatus: ["Never Married", "Divorced", "Widowed", "Separated"],
  haveChildren: ["Yes", "No"],
  wantMoreChildren: ["Yes", "No", "Not sure"],
  relocate: ["Yes", "No", "Maybe"],
  bornReverted: ["Born Muslim", "Reverted"],
  religiousValues: ["Very Conservative", "Conservative", "Moderate", "Liberal"],
  attendReligiousServices: ["Daily", "Weekly", "Monthly", "Rarely", "Never"],
  readQuran: ["Daily", "Weekly", "Monthly", "Rarely", "Never"],
  familyValues: ["Traditional", "Modern", "Moderate"],
  languages: [
    "Arabic",
    "English",
    "French",
    "Spanish",
    "Urdu",
    "Turkish",
    "Other",
  ],
  employmentStatus: [
    "Any",
    "Retired",
    "Not Employed",
    "Student",
    "Part Time",
    "Other",
    "Full Time",
    "Prefer not to say",
    "Homemaker",
  ],
  livingSituation: [
    "Any",
    "Live Alone",
    "Live with friends",
    "Live with family",
    "Live with spouse",
    "Live with kids",
    "Other",
    "Prefer not to say",
  ],
};

export const SECTIONS = [
  {
    id: "basicInfo",
    title: "Basic Information",
    icon: User,
    description: "Your basic personal details",
    fields: [
      {
        key: "gender",
        label: "Gender",
        type: "radio",
        options: FIELD_OPTIONS.gender,
      },
      { key: "age", label: "Age", type: "number" },
      { key: "livesIn", label: "Lives In", type: "text" },
      {
        key: "relocate",
        label: "Willing to Relocate",
        type: "radio",
        options: FIELD_OPTIONS.relocate,
      },
    ],
  },
  {
    id: "appearance",
    title: "Appearance",
    icon: Eye,
    description: "Your physical characteristics",
    fields: [
      {
        key: "hairColor",
        label: "Hair Color",
        type: "radio",
        options: FIELD_OPTIONS.hairColor,
      },
      {
        key: "eyeColor",
        label: "Eye Color",
        type: "radio",
        options: FIELD_OPTIONS.eyeColor,
      },
      { key: "height", label: "Height", type: "text" },
      { key: "weight", label: "Weight", type: "text" },
      {
        key: "bodyStyle",
        label: "Body Style",
        type: "radio",
        options: FIELD_OPTIONS.bodyStyle,
      },
      {
        key: "ethnicity",
        label: "Ethnicity",
        type: "radio",
        options: FIELD_OPTIONS.ethnicity,
      },
    ],
  },
  {
    id: "lifestyle",
    title: "Lifestyle",
    icon: Coffee,
    description: "Your daily habits and living situation",
    fields: [
      { key: "occupation", label: "Occupation", type: "text" },
      {
        key: "smoke",
        label: "Smoking",
        type: "radio",
        options: FIELD_OPTIONS.smoke,
      },
      { key: "eatingHabits", label: "Eating Habits", type: "text" },
      {
        key: "maritalStatus",
        label: "Marital Status",
        type: "radio",
        options: FIELD_OPTIONS.maritalStatus,
      },
      {
        key: "haveChildren",
        label: "Have Children",
        type: "radio",
        options: FIELD_OPTIONS.haveChildren,
      },
      {
        key: "wantMoreChildren",
        label: "Want More Children",
        type: "radio",
        options: FIELD_OPTIONS.wantMoreChildren,
      },
      {
        key: "employmentStatus",
        label: "Employment Status",
        type: "radio",
        options: FIELD_OPTIONS.employmentStatus,
      },
      {
        key: "annualIncome",
        label: "Annual Income",
        type: "number",
      },
      {
        key: "livingSituation",
        label: "Living Situation",
        type: "radio",
        options: FIELD_OPTIONS.livingSituation,
      },
    ],
  },
  {
    id: "education",
    title: "Education",
    icon: GraduationCap,
    description: "Your educational background",
    fields: [{ key: "education", label: "Education Level", type: "text" }],
  },
  {
    id: "religious",
    title: "Religious & Cultural",
    icon: BookOpen,
    description: "Your religious and cultural background",
    fields: [
      { key: "religion", label: "Religion", type: "text" },
      { key: "nationality", label: "Nationality", type: "text" },
      {
        key: "languagesSpoken",
        label: "Languages Spoken",
        type: "checkbox",
        options: FIELD_OPTIONS.languages,
      },
      {
        key: "bornReverted",
        label: "Born/Reverted",
        type: "radio",
        options: FIELD_OPTIONS.bornReverted,
      },
      {
        key: "religiousValues",
        label: "Religious Values",
        type: "radio",
        options: FIELD_OPTIONS.religiousValues,
      },
      {
        key: "attendReligiousServices",
        label: "Attend Religious Services",
        type: "radio",
        options: FIELD_OPTIONS.attendReligiousServices,
      },
      {
        key: "readQuran",
        label: "Read Quran",
        type: "radio",
        options: FIELD_OPTIONS.readQuran,
      },
      {
        key: "familyValues",
        label: "Family Values",
        type: "radio",
        options: FIELD_OPTIONS.familyValues,
      },
    ],
  },
];
