import {
  User,
  Heart,
  Eye,
  Smile,
  Coffee,
  BookOpen,
  MapPin,
  Calendar,
  Ruler,
  Scale,
  Users,
  GraduationCap,
  Languages,
  Star,
  Cigarette,
  Baby,
  Utensils,
  Briefcase,
  Home,
} from "lucide-react";
import { GiDiamondRing } from "react-icons/gi";

export const profileSectionsConfig = [
  {
    title: "Basic Information",
    icon: <User className="w-5 h-5 text-primary-color1" />,
    personalData: "basicInfo",
    seekingData: "basic",
    fields: [
      {
        key: "gender",
        label: "Gender",
        icon: <User className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "age",
        label: "Age",
        icon: <Calendar className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "livesIn",
        label: "Lives In",
        icon: <MapPin className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "relocate",
        label: "Willing to Relocate",
        icon: <Star className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "lookingFor",
        label: "Looking For",
        icon: <User className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "ageRange",
        label: "Age Range",
        icon: <Calendar className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "locationPreference",
        label: "Location Preference",
        icon: <MapPin className="w-4 h-4" />,
        section: "seeking",
      },
    ],
  },  
  {
    title: "Appearance",
    icon: <Eye className="w-5 h-5 text-primary-color1" />,
    personalData: "appearance",
    seekingData: "appearance",
    fields: [
      {
        key: "hairColor",
        label: "Hair Color",
        icon: <Smile className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "eyeColor",
        label: "Eye Color",
        icon: <Eye className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "height",
        label: "Height",
        icon: <Ruler className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "weight",
        label: "Weight",
        icon: <Scale className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "bodyStyle",
        label: "Body Style",
        icon: <User className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "ethnicity",
        label: "Ethnicity",
        icon: <Users className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "hairColor",
        label: "Hair Color",
        icon: <Smile className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "eyeColor",
        label: "Eye Color",
        icon: <Eye className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "height",
        label: "Height",
        icon: <Ruler className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "weight",
        label: "Weight",
        icon: <Scale className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "bodyStyle",
        label: "Body Style",
        icon: <User className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "ethnicity",
        label: "Ethnicity",
        icon: <Users className="w-4 h-4" />,
        section: "seeking",
      },
    ],
  },
  {
    title: "Lifestyle",
    icon: <Coffee className="w-5 h-5 text-primary-color1" />,
    personalData: "lifestyle",
    seekingData: "lifestyle",
    fields: [
      {
        key: "occupation",
        label: "Occupation",
        icon: <Briefcase className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "smoke",
        label: "Smoking",
        icon: <Cigarette className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "eatingHabits",
        label: "Eating Habits",
        icon: <Utensils className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "maritalStatus",
        label: "Marital Status",
        icon: <GiDiamondRing className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "haveChildren",
        label: "Have Children",
        icon: <Baby className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "wantMoreChildren",
        label: "Want More Children",
        icon: <Baby className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "employmentStatus",
        label: "Employment Status",
        icon: <Briefcase className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "livingSituation",
        label: "Living Situation",
        icon: <Home className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "smoke",
        label: "Smoking",
        icon: <Cigarette className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "maritalStatus",
        label: "Marital Status",
        icon: <GiDiamondRing className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "wantChildren",
        label: "Want Children",
        icon: <Baby className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "eatingHabits",
        label: "Eating Habits",
        icon: <Utensils className="w-4 h-4" />,
        section: "seeking",
      },
    ],
  },
  {
    title: "Education",
    icon: <GraduationCap className="w-5 h-5 text-primary-color1" />,
    personalData: "education",
    seekingData: "religious",
    fields: [
      {
        key: "education",
        label: "Education Level",
        icon: <GraduationCap className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "education",
        label: "Education",
        icon: <GraduationCap className="w-4 h-4" />,
        section: "seeking",
      },
    ],
  },
  {
    title: "Religious & Cultural Background",
    icon: <BookOpen className="w-5 h-5 text-primary-color1" />,
    personalData: "religious",
    seekingData: "religious",
    fields: [
      {
        key: "religion",
        label: "Religion",
        icon: <BookOpen className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "nationality",
        label: "Nationality",
        icon: <MapPin className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "education",
        label: "Education",
        icon: <GraduationCap className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "languagesSpoken",
        label: "Languages Spoken",
        icon: <Languages className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "bornReverted",
        label: "Born/Reverted",
        icon: <User className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "religiousValues",
        label: "Religious Values",
        icon: <BookOpen className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "attendReligiousServices",
        label: "Attend Religious Services",
        icon: <BookOpen className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "readQuran",
        label: "Read Quran",
        icon: <BookOpen className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "familyValues",
        label: "Family Values",
        icon: <Users className="w-4 h-4" />,
        section: "personal",
      },
      {
        key: "religion",
        label: "Religion",
        icon: <BookOpen className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "nationality",
        label: "Nationality",
        icon: <MapPin className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "education",
        label: "Education",
        icon: <GraduationCap className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "languages",
        label: "Languages",
        icon: <Languages className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "hijab",
        label: "Hijab",
        icon: <User className="w-4 h-4" />,
        section: "seeking",
      },
      {
        key: "niqab",
        label: "Niqab",
        icon: <Eye className="w-4 h-4" />,
        section: "seeking",
      },
    ],
  },
];
