import { images } from "./images";

export const userData = {
  name: "Lora Ahmad",
  email: "wedadjoulaq@gmail.com",
  phone: "(+963) 987356113",
  photo: images.avatar,
  introduction:
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque nostrum earum libero accusamus, cum quaerat possimus fugit quia error. Ipsa vel quam enim iusto pariatur perferendis maxime laborum, ex libero.",
  details: {
    weight: "35 kg",
    place: "Jordan",
    religion: "muslim",
    education: "it engineering",
    maritalStatus: "single",
    height: "170 cm",
    occupation: "designer",
    age: "24",
    jobTitle: "UI - UX designer",
  },
};

export const mockPhotos: Photo[] = [
  {
    id: "1",
    url: "/images/userTest.jpg",
  },
  {
    id: "2",
    url: "/images/userTest.jpg",
  },
  {
    id: "3",
    url: "/images/userTest.jpg",
  },
  {
    id: "4",
    url: "/images/userTest.jpg",
  },
  {
    id: "5",
    url: "/images/userTest.jpg",
  },
  {
    id: "6",
    url: "/images/userTest.jpg",
  },
  {
    id: "7",
    url: "/images/userTest.jpg",
  },
  {
    id: "8",
    url: "/images/userTest.jpg",
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "success",
    title: "Payment Received",
    message: "Your payment of $250 has been successfully processed.",
    timestamp: new Date("2024-01-15T10:30:00"),
    read: false,
  },
  {
    id: "2",
    type: "warning",
    title: "Subscription Expiring",
    message: "Your premium subscription expires in 3 days.",
    timestamp: new Date("2024-01-15T09:15:00"),
    read: false,
  },
  {
    id: "3",
    type: "info",
    title: "New Feature Available",
    message: "Check out the new dashboard analytics feature.",
    timestamp: new Date("2024-01-14T16:45:00"),
    read: true,
  },
  {
    id: "4",
    type: "error",
    title: "Login Attempt Failed",
    message: "There was an unsuccessful login attempt from a new device.",
    timestamp: new Date("2024-01-14T14:20:00"),
    read: true,
  },
  {
    id: "5",
    type: "system",
    title: "System Maintenance",
    message: "Scheduled maintenance this Sunday from 2-4 AM.",
    timestamp: new Date("2024-01-13T11:00:00"),
    read: true,
  },
  {
    id: "6",
    type: "success",
    title: "Profile Updated",
    message: "Your profile information has been successfully updated.",
    timestamp: new Date("2024-01-13T10:30:00"),
    read: true,
  },
];

export const people: Person[] = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    city: "New York",
    status: "Single",
    occupation: "Software Engineer",
    education: "Bachelor's",
    image: "/images/userTest.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 32,
    city: "Los Angeles",
    status: "Married",
    occupation: "Product Manager",
    education: "Master's",
    image: "/images/userTest.jpg",
  },
  {
    id: 3,
    name: "Mike Johnson",
    age: 25,
    city: "Chicago",
    status: "Single",
    occupation: "Data Scientist",
    education: "PhD",
    image: "/images/userTest.jpg",
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: "101",
    reporter: {
      id: 1,
      name: "Ahmed Mohamed",
      email: "ahmed@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-01-15",
      lastLogin: "2024-10-01 09:30",
      reportsCount: 2,
      marriageRequests: 1,
      activeChats: 3,
    },
    reportedUser: {
      id: 2,
      name: "Sara Khalid",
      email: "sara@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-02-20",
      lastLogin: "2024-10-01 08:45",
      reportsCount: 1,
      marriageRequests: 0,
      activeChats: 5,
    },
    type: "harassment",
    date: "2024-10-01 10:30",
    status: "pending",
    description:
      "User sent inappropriate messages repeatedly despite requests to stop",
    attachments: ["screenshot1.jpg", "chat_log.pdf"],
    wasBanned: false,
  },
  {
    id: "102",
    reporter: {
      id: 3,
      name: "Mohamed Ali",
      email: "mohamed@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-03-10",
      lastLogin: "2024-10-01 08:20",
      reportsCount: 0,
      marriageRequests: 2,
      activeChats: 4,
    },
    reportedUser: {
      id: 4,
      name: "Fatima Noor",
      email: "fatima@example.com",
      status: "pending",
      verification: "pending",
      registrationDate: "2024-09-15",
      lastLogin: "2024-09-30 22:15",
      reportsCount: 3,
      marriageRequests: 1,
      activeChats: 2,
    },
    type: "inappropriate",
    date: "2024-10-01 09:15",
    status: "pending",
    description: "Sharing inappropriate images on the platform",
    attachments: ["image1.png"],
    wasBanned: false,
  },
  {
    id: "103",
    reporter: {
      id: 5,
      name: "Khalid Hassan",
      email: "khalid@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-01-05",
      lastLogin: "2024-09-30 20:30",
      reportsCount: 1,
      marriageRequests: 0,
      activeChats: 6,
    },
    reportedUser: {
      id: 6,
      name: "Layla Ahmed",
      email: "layla@example.com",
      status: "banned",
      verification: "unverified",
      registrationDate: "2024-09-20",
      lastLogin: "2024-09-30 18:00",
      reportsCount: 5,
      marriageRequests: 0,
      activeChats: 0,
    },
    type: "fake",
    date: "2024-09-30 16:45",
    status: "resolved",
    description: "Fake profile using stolen pictures",
    attachments: ["profile_comparison.jpg", "original_source.pdf"],
    wasBanned: true,
  },
  {
    id: "104",
    reporter: {
      id: 7,
      name: "Noura Abdullah",
      email: "noura@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-04-12",
      lastLogin: "2024-09-30 19:10",
      reportsCount: 0,
      marriageRequests: 3,
      activeChats: 7,
    },
    reportedUser: {
      id: 8,
      name: "Omar Saleh",
      email: "omar@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-05-22",
      lastLogin: "2024-09-30 16:30",
      reportsCount: 2,
      marriageRequests: 1,
      activeChats: 8,
    },
    type: "spam",
    date: "2024-09-30 14:20",
    status: "pending",
    description: "Excessive messaging and promotional content",
    attachments: ["chat_history.txt", "promotional_messages.jpg"],
    wasBanned: false,
  },
  {
    id: "105",
    reporter: {
      id: 9,
      name: "Rashid Al-Mansoor",
      email: "rashid@example.com",
      status: "active",
      verification: "verified",
      registrationDate: "2024-06-18",
      lastLogin: "2024-09-30 12:45",
      reportsCount: 1,
      marriageRequests: 0,
      activeChats: 2,
    },
    reportedUser: {
      id: 10,
      name: "Aisha Jamil",
      email: "aisha@example.com",
      status: "inactive",
      verification: "verified",
      registrationDate: "2024-03-30",
      lastLogin: "2024-09-28 11:20",
      reportsCount: 0,
      marriageRequests: 2,
      activeChats: 1,
    },
    type: "other",
    date: "2024-09-30 11:30",
    status: "rejected",
    description: "Personal disagreement over marriage proposal",
    attachments: [],
    wasBanned: false,
  },
];

export const MOCK_STATISTICS = {
  overview: {
    totalComplaints: 1247,
    pending: 89,
    resolved: 987,
    rejected: 171,
    resolutionRate: 79.2,
    avgResolutionTime: "2.3 days",
  },
  byType: [
    {
      type: "Harassment",
      count: 456,
      trend: "up" as const,
      percentage: 36.6,
      color: "#ef4444",
    },
    {
      type: "Fake Profile",
      count: 289,
      trend: "down" as const,
      percentage: 23.2,
      color: "#f59e0b",
    },
    {
      type: "Inappropriate Content",
      count: 198,
      trend: "up" as const,
      percentage: 15.9,
      color: "#8b5cf6",
    },
    {
      type: "Spam",
      count: 156,
      trend: "stable" as const,
      percentage: 12.5,
      color: "#06b6d4",
    },
    {
      type: "Other",
      count: 148,
      trend: "stable" as const,
      percentage: 11.9,
      color: "#10b981",
    },
  ],
  monthlyTrend: [
    { month: "Jan", complaints: 98, resolved: 75 },
    { month: "Feb", complaints: 112, resolved: 89 },
    { month: "Mar", complaints: 105, resolved: 82 },
    { month: "Apr", complaints: 124, resolved: 98 },
    { month: "May", complaints: 156, resolved: 124 },
    { month: "Jun", complaints: 143, resolved: 115 },
    { month: "Jul", complaints: 167, resolved: 132 },
    { month: "Aug", complaints: 189, resolved: 156 },
    { month: "Sep", complaints: 175, resolved: 142 },
    { month: "Oct", complaints: 198, resolved: 162 },
  ],
};
